version: "3.8"
# * =============================================== global networks and volumes =============================================== * #
networks:
  caddy:
  unami:
  changedetection:


volumes: {}

services:
  # * =============================================== caddy =============================================== * #
  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./env/Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy:/data
      - ./config/caddy:/config
    networks:
      - caddy

  # * =============================================== unami =============================================== * #
  unami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    environment:
      DATABASE_URL: postgresql://umami:umami@unami-db:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: randomhashsalt
    depends_on:
      - unami-db
    restart: always
    networks:
      - caddy
      - unami

  unami-db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - ./env/unami.schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - ./data/umami:/var/lib/postgresql/data
    restart: always
    networks:
      - unami

  # * =============================================== changedetection =============================================== * #
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io:latest
    container_name: changedetection
    hostname: changedetection
    volumes:
      - ./data/changedetection:/datastore
    environment:
      - BASE_URL=https://changedetection.ziyixi.science
      - USE_X_SETTINGS=1
      - FETCH_WORKERS=2
    restart: always
    networks:
      - caddy
      - changedetection

  browser-chrome:
    hostname: browser-chrome
    image: selenium/standalone-chrome-debug:latest
    environment:
      - VNC_NO_PASSWORD=1
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
    volumes:
      - /dev/shm:/dev/shm
    restart: always
    networks:
      - changedetection

  # * =============================================== flame =============================================== * #
  flame:
    image: pawelmalak/flame:latest
    container_name: flame
    volumes:
      - ./data/flame:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: ./env/flame.env
    restart: always
    networks:
      - caddy

  # * =============================================== backup =============================================== * #
  backup:
    image: offen/docker-volume-backup:latest
    restart: always
    env_file: ./env/backup.env
    volumes:
      - ./data:/backup/data:ro
      - ./config:/backup/config:ro
      - ./env:/backup/env:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro