version: "3.8"

services:
  # * =============================================== shadowsocks =============================================== * #
  shadowsocks:
    image: teddysun/shadowsocks-libev:latest
    ports:
      - "8388:8388"
    restart: always
    volumes:
      - ./env/config.json:/etc/shadowsocks-libev/config.json

  # * =============================================== frp =============================================== * #
  frp:
    # ref: https://calxu.github.io/note/20200301_vpn_2/
    image: snowdreamtech/frpc:latest
    container_name: frp
    restart: always
    volumes:
      - ./env/frpc.ini:/etc/frp/frpc.ini
