version: "3.8"

services:
  # * =============================================== shadowsocks =============================================== * #
  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    ports:
      - "8388:8388"
    environment:
      - METHOD=aes-256-gcm
      - PASSWORD=changemelater
      - TIMEOUT=30000
    restart: always

  # * =============================================== frp =============================================== * #
  frp:
    # ref: https://calxu.github.io/note/20200301_vpn_2/
    image: snowdreamtech/frpc:latest
    container_name: frp
    restart: always
    volumes:
      - ./env/frpc.ini:/etc/frp/frpc.ini
